/** @jsxImportSource @emotion/react */

import type { Meta, StoryObj } from '@storybook/react';
import themeDecorator from '../themeDecorator';
import Accordion from '../../src/common/Accordion/Accordion';
import { DictionaryDownloadButtonProps } from '../../src/viewer-table/InteractionPanel/DownloadTemplatesButton';

const meta = {
	component: Accordion,
	title: 'Common/Accordion',
	tags: ['autodocs'],
	decorators: [themeDecorator()],
} satisfies Meta<typeof Accordion>;

export default meta;
type Story = StoryObj<typeof meta>;

const mockDictionaryDownloadButtonProps: DictionaryDownloadButtonProps = {
	version: '1.0',
	name: 'example-dictionary',
	lecternUrl: 'localhost:3031',
	fileType: 'tsv',
	iconOnly: true,
	disabled: true,
};
export const Default: Story = {
	args: {
		accordionItems: [
			{
				title: '{Schema:name}',
				openOnInit: false,
				description:
					'{Schema: description} Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
				content: 'Content for item 1',
				dictionaryDownloadButtonProps: mockDictionaryDownloadButtonProps,
			},
			{
				title: '{Schema:name}',
				openOnInit: false,
				description:
					'{Schema: description} Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
				content:
					'Paritur Lorem sint commodo deserunt duis nostrud. Quis cillum veniam dolor amet elit nulla. Pariatur sunt ex non minim labore et exercitation quis velit duis. Nisi minim commodo anim aute quis incididunt proident enim adipisicing eu do. Mollit tempor minim anim deserunt adipisicing. Magna esse labore eiusmod irure sunt cupidatat non et labore. Pariatur consectetur cupidatat ullamco dolor sit commodo proident cupidatat nulla occaecat qui ea. Ad nostrud magna quis anim veniam laboris do sint cillum nisi. Et sint enim eu proident ipsum. Deserunt ad ex non aliquip fugiat eiusmod tempor fugiat est et excepteur consequat excepteur ipsum.Quis consectetur nostrud proident laboris veniam eiusmod ullamco culpa esse reprehenderit esse proident sint. Ea aliqua laboris veniam tempor eiusmod sunt consequat nisi mollit. Veniam enim est cillum mollit sunt in non. Elit voluptate aliquip sunt fugiat aliqua elit incididunt fugiat ipsum eu mollit tempor. Officia magna est est cillum qui amet fugiat quis. Consectetur quis deserunt enim eiusmod est est sint quis consectetur nulla ea non. Magna ipsum aute laborum nisi duis tempor dolor ad cupidatat quis et pariatur.Sit ad irure laborum minim deserunt aute mollit fugiat minim laboris. Laborum aliqua occaecat dolore esse exercitation do elit aliquip amet proident laborum sint. Aute do cupidatat ut ea ipsum nisi veniam nulla ea est ex irure adipisicing adipisicing. In dolor aliquip non magna mollit reprehenderit sit fugiat excepteur. Pariatur tempor excepteur nulla tempor commodo reprehenderit deserunt sint nisi aute. Dolore est aliquip eu nisi ea nisi mollit culpa magna.Adipisicing ea sunt ullamco voluptate tempor eu.Sint ex officiaLorem laborum mollit proident sunt culpa deserunt. officia enim. ',
				dictionaryDownloadButtonProps: mockDictionaryDownloadButtonProps,
			},
			{
				title: '{An_unnecessarily_lengthy_name_for_a_schema:with_it’s_name_include_of_course}',
				openOnInit: false,
				description:
					'{Schema: description} Do MagNisiDoAmet sit adipisicing dolore incididunt minim.lore pariatur sit ex eiusmod Lorem do voluptate id aliquip occaecat duis. laMinim fugiatEnim qui irure incididunt ex proident qui reprehenderit enim. deserunt irure mollit do aute do voluptate sint veniam commodo excepteur officia.borum mollit aute eu ea dolor adipisicing et.na Cupidatat nostrud adipisicing nulla fugiat laboris laborum aliquip adipisicing minim incididunt laboris.non ipsum dolore anim eiusmod velit amet enim veniam ut ad est.fugiat nisi elit nisi non aliqua qui duis et consectetur.Labore proident qui id ad laborum mollit amet do officia sint qui mollit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cillum ex qui pariatur sint est elit amet commodo dolore duis exercitation cupidatat anim deserunt. Commodo mollit labore et qui sit consectetur laborum eiusmod.',
				content:
					'Paritur Lorem sint commodo deserunt duis nostrud. Quis cillum veniam dolor amet elit nulla. Pariatur sunt ex non minim labore et exercitation quis velit duis. Nisi minim commodo anim aute quis incididunt proident enim adipisicing eu do. Mollit tempor minim anim deserunt adipisicing. Magna esse labore eiusmod irure sunt cupidatat non et labore. Pariatur consectetur cupidatat ullamco dolor sit commodo proident cupidatat nulla occaecat qui ea. Ad nostrud magna quis anim veniam laboris do sint cillum nisi. Et sint enim eu proident ipsum. Deserunt ad ex non aliquip fugiat eiusmod tempor fugiat est et excepteur consequat excepteur ipsum.Quis consectetur nostrud proident laboris veniam eiusmod ullamco culpa esse reprehenderit esse proident sint. Ea aliqua laboris veniam tempor eiusmod sunt consequat nisi mollit. Veniam enim est cillum mollit sunt in non. Elit voluptate aliquip sunt fugiat aliqua elit incididunt fugiat ipsum eu mollit tempor. Officia magna est est cillum qui amet fugiat quis. Consectetur quis deserunt enim eiusmod est est sint quis consectetur nulla ea non. Magna ipsum aute laborum nisi duis tempor dolor ad cupidatat quis et pariatur.Sit ad irure laborum minim deserunt aute mollit fugiat minim laboris. Laborum aliqua occaecat dolore esse exercitation do elit aliquip amet proident laborum sint. Aute do cupidatat ut ea ipsum nisi veniam nulla ea est ex irure adipisicing adipisicing. In dolor aliquip non magna mollit reprehenderit sit fugiat excepteur. Pariatur tempor excepteur nulla tempor commodo reprehenderit deserunt sint nisi aute. Dolore est aliquip eu nisi ea nisi mollit culpa magna. ',
				dictionaryDownloadButtonProps: mockDictionaryDownloadButtonProps,
			},
			{
				title: '{An_unnecessarily_lengthy_name_for_a_schema:with_it’s_name_include_of_course}',
				openOnInit: false,
				description:
					'{Schema: description} Do MagNisiDoAmet sit adipisicing dolore incididunt minim.lore pariatur sit ex eiusmod Lorem do voluptate id aliquip occaecat duis. laMinim fugiatEnim qui irure incididunt ex proident qui reprehenderit enim. deserunt irure mollit do aute do voluptate sint veniam commodo excepteur officia.borum mollit aute eu ea dolor adipisicing et.na Cupidatat nostrud adipisicing nulla fugiat laboris laborum aliquip adipisicing minim incididunt laboris.non ipsum dolore anim eiusmod velit amet enim veniam ut ad est.fugiat nisi elit nisi non aliqua qui duis et consectetur.Labore proident qui id ad laborum mollit amet do officia sint qui mollit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cillum ex qui pariatur sint est elit amet commodo dolore duis exercitation cupidatat anim deserunt. Commodo mollit labore et qui sit consectetur laborum eiusmod.',
				content:
					'Paritur Lorem sint commodo deserunt duis nostrud. Quis cillum veniam dolor amet elit nulla. Pariatur sunt ex non minim labore et exercitation quis velit duis. Nisi minim commodo anim aute quis incididunt proident enim adipisicing eu do. Mollit tempor minim anim deserunt adipisicing. Magna esse labore eiusmod irure sunt cupidatat non et labore. Pariatur consectetur cupidatat ullamco dolor sit commodo proident cupidatat nulla occaecat qui ea. Ad nostrud magna quis anim veniam laboris do sint cillum nisi. Et sint enim eu proident ipsum. Deserunt ad ex non aliquip fugiat eiusmod tempor fugiat est et excepteur consequat excepteur ipsum.Quis consectetur nostrud proident laboris veniam eiusmod ullamco culpa esse reprehenderit esse proident sint. Ea aliqua laboris veniam tempor eiusmod sunt consequat nisi mollit. Veniam enim est cillum mollit sunt in non. Elit voluptate aliquip sunt fugiat aliqua elit incididunt fugiat ipsum eu mollit tempor. Officia magna est est cillum qui amet fugiat quis. Consectetur quis deserunt enim eiusmod est est sint quis consectetur nulla ea non. Magna ipsum aute laborum nisi duis tempor dolor ad cupidatat quis et pariatur.Sit ad irure laborum minim deserunt aute mollit fugiat minim laboris. Laborum aliqua occaecat dolore esse exercitation do elit aliquip amet proident laborum sint. Aute do cupidatat ut ea ipsum nisi veniam nulla ea est ex irure adipisicing adipisicing. In dolor aliquip non magna mollit reprehenderit sit fugiat excepteur. Pariatur tempor excepteur nulla tempor commodo reprehenderit deserunt sint nisi aute. Dolore est aliquip eu nisi ea nisi mollit culpa magna. ',
				dictionaryDownloadButtonProps: mockDictionaryDownloadButtonProps,
			},
			{
				title: '{An_unnecessarily_lengthy_name_for_a_schema:with_it’s_name_include_of_course}',
				openOnInit: false,
				description:
					'{Schema: description} Do MagNisiDoAmet sit adipisicing dolore incididunt minim.lore pariatur sit ex eiusmod Lorem do voluptate id aliquip occaecat duis. laMinim fugiatEnim qui irure incididunt ex proident qui reprehenderit enim. deserunt irure mollit do aute do voluptate sint veniam commodo excepteur officia.borum mollit aute eu ea dolor adipisicing et.na Cupidatat nostrud adipisicing nulla fugiat laboris laborum aliquip adipisicing minim incididunt laboris.non ipsum dolore anim eiusmod velit amet enim veniam ut ad est.fugiat nisi elit nisi non aliqua qui duis et consectetur.Labore proident qui id ad laborum mollit amet do officia sint qui mollit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cillum ex qui pariatur sint est elit amet commodo dolore duis exercitation cupidatat anim deserunt. Commodo mollit labore et qui sit consectetur laborum eiusmod.',
				content:
					'Paritur Lorem sint commodo deserunt duis nostrud. Quis cillum veniam dolor amet elit nulla. Pariatur sunt ex non minim labore et exercitation quis velit duis. Nisi minim commodo anim aute quis incididunt proident enim adipisicing eu do. Mollit tempor minim anim deserunt adipisicing. Magna esse labore eiusmod irure sunt cupidatat non et labore. Pariatur consectetur cupidatat ullamco dolor sit commodo proident cupidatat nulla occaecat qui ea. Ad nostrud magna quis anim veniam laboris do sint cillum nisi. Et sint enim eu proident ipsum. Deserunt ad ex non aliquip fugiat eiusmod tempor fugiat est et excepteur consequat excepteur ipsum.Quis consectetur nostrud proident laboris veniam eiusmod ullamco culpa esse reprehenderit esse proident sint. Ea aliqua laboris veniam tempor eiusmod sunt consequat nisi mollit. Veniam enim est cillum mollit sunt in non. Elit voluptate aliquip sunt fugiat aliqua elit incididunt fugiat ipsum eu mollit tempor. Officia magna est est cillum qui amet fugiat quis. Consectetur quis deserunt enim eiusmod est est sint quis consectetur nulla ea non. Magna ipsum aute laborum nisi duis tempor dolor ad cupidatat quis et pariatur.Sit ad irure laborum minim deserunt aute mollit fugiat minim laboris. Laborum aliqua occaecat dolore esse exercitation do elit aliquip amet proident laborum sint. Aute do cupidatat ut ea ipsum nisi veniam nulla ea est ex irure adipisicing adipisicing. In dolor aliquip non magna mollit reprehenderit sit fugiat excepteur. Pariatur tempor excepteur nulla tempor commodo reprehenderit deserunt sint nisi aute. Dolore est aliquip eu nisi ea nisi mollit culpa magna. ',
				dictionaryDownloadButtonProps: mockDictionaryDownloadButtonProps,
			},
			{
				title: '{An_unnecessarily_lengthy_name_for_a_schema:with_it’s_name_include_of_course}',
				openOnInit: false,
				description:
					'{Schema: description} Do MagNisiDoAmet sit adipisicing dolore incididunt minim.lore pariatur sit ex eiusmod Lorem do voluptate id aliquip occaecat duis. laMinim fugiatEnim qui irure incididunt ex proident qui reprehenderit enim. deserunt irure mollit do aute do voluptate sint veniam commodo excepteur officia.borum mollit aute eu ea dolor adipisicing et.na Cupidatat nostrud adipisicing nulla fugiat laboris laborum aliquip adipisicing minim incididunt laboris.non ipsum dolore anim eiusmod velit amet enim veniam ut ad est.fugiat nisi elit nisi non aliqua qui duis et consectetur.Labore proident qui id ad laborum mollit amet do officia sint qui mollit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cillum ex qui pariatur sint est elit amet commodo dolore duis exercitation cupidatat anim deserunt. Commodo mollit labore et qui sit consectetur laborum eiusmod.',
				content:
					'Paritur Lorem sint commodo deserunt duis nostrud. Quis cillum veniam dolor amet elit nulla. Pariatur sunt ex non minim labore et exercitation quis velit duis. Nisi minim commodo anim aute quis incididunt proident enim adipisicing eu do. Mollit tempor minim anim deserunt adipisicing. Magna esse labore eiusmod irure sunt cupidatat non et labore. Pariatur consectetur cupidatat ullamco dolor sit commodo proident cupidatat nulla occaecat qui ea. Ad nostrud magna quis anim veniam laboris do sint cillum nisi. Et sint enim eu proident ipsum. Deserunt ad ex non aliquip fugiat eiusmod tempor fugiat est et excepteur consequat excepteur ipsum.Quis consectetur nostrud proident laboris veniam eiusmod ullamco culpa esse reprehenderit esse proident sint. Ea aliqua laboris veniam tempor eiusmod sunt consequat nisi mollit. Veniam enim est cillum mollit sunt in non. Elit voluptate aliquip sunt fugiat aliqua elit incididunt fugiat ipsum eu mollit tempor. Officia magna est est cillum qui amet fugiat quis. Consectetur quis deserunt enim eiusmod est est sint quis consectetur nulla ea non. Magna ipsum aute laborum nisi duis tempor dolor ad cupidatat quis et pariatur.Sit ad irure laborum minim deserunt aute mollit fugiat minim laboris. Laborum aliqua occaecat dolore esse exercitation do elit aliquip amet proident laborum sint. Aute do cupidatat ut ea ipsum nisi veniam nulla ea est ex irure adipisicing adipisicing. In dolor aliquip non magna mollit reprehenderit sit fugiat excepteur. Pariatur tempor excepteur nulla tempor commodo reprehenderit deserunt sint nisi aute. Dolore est aliquip eu nisi ea nisi mollit culpa magna. ',
				dictionaryDownloadButtonProps: mockDictionaryDownloadButtonProps,
			},
			{
				title: '{An_unnecessarily_lengthy_name_for_a_schema:with_it’s_name_include_of_course}',
				openOnInit: false,
				description:
					'{Schema: description} Do MagNisiDoAmet sit adipisicing dolore incididunt minim.lore pariatur sit ex eiusmod Lorem do voluptate id aliquip occaecat duis. laMinim fugiatEnim qui irure incididunt ex proident qui reprehenderit enim. deserunt irure mollit do aute do voluptate sint veniam commodo excepteur officia.borum mollit aute eu ea dolor adipisicing et.na Cupidatat nostrud adipisicing nulla fugiat laboris laborum aliquip adipisicing minim incididunt laboris.non ipsum dolore anim eiusmod velit amet enim veniam ut ad est.fugiat nisi elit nisi non aliqua qui duis et consectetur.Labore proident qui id ad laborum mollit amet do officia sint qui mollit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cillum ex qui pariatur sint est elit amet commodo dolore duis exercitation cupidatat anim deserunt. Commodo mollit labore et qui sit consectetur laborum eiusmod.',
				content:
					'Paritur Lorem sint commodo deserunt duis nostrud. Quis cillum veniam dolor amet elit nulla. Pariatur sunt ex non minim labore et exercitation quis velit duis. Nisi minim commodo anim aute quis incididunt proident enim adipisicing eu do. Mollit tempor minim anim deserunt adipisicing. Magna esse labore eiusmod irure sunt cupidatat non et labore. Pariatur consectetur cupidatat ullamco dolor sit commodo proident cupidatat nulla occaecat qui ea. Ad nostrud magna quis anim veniam laboris do sint cillum nisi. Et sint enim eu proident ipsum. Deserunt ad ex non aliquip fugiat eiusmod tempor fugiat est et excepteur consequat excepteur ipsum.Quis consectetur nostrud proident laboris veniam eiusmod ullamco culpa esse reprehenderit esse proident sint. Ea aliqua laboris veniam tempor eiusmod sunt consequat nisi mollit. Veniam enim est cillum mollit sunt in non. Elit voluptate aliquip sunt fugiat aliqua elit incididunt fugiat ipsum eu mollit tempor. Officia magna est est cillum qui amet fugiat quis. Consectetur quis deserunt enim eiusmod est est sint quis consectetur nulla ea non. Magna ipsum aute laborum nisi duis tempor dolor ad cupidatat quis et pariatur.Sit ad irure laborum minim deserunt aute mollit fugiat minim laboris. Laborum aliqua occaecat dolore esse exercitation do elit aliquip amet proident laborum sint. Aute do cupidatat ut ea ipsum nisi veniam nulla ea est ex irure adipisicing adipisicing. In dolor aliquip non magna mollit reprehenderit sit fugiat excepteur. Pariatur tempor excepteur nulla tempor commodo reprehenderit deserunt sint nisi aute. Dolore est aliquip eu nisi ea nisi mollit culpa magna. ',
				dictionaryDownloadButtonProps: mockDictionaryDownloadButtonProps,
			},
			{
				title: '{An_unnecessarily_lengthy_name_for_a_schema:with_it’s_name_include_of_course}',
				openOnInit: false,
				description:
					'{Schema: description} Do MagNisiDoAmet sit adipisicing dolore incididunt minim.lore pariatur sit ex eiusmod Lorem do voluptate id aliquip occaecat duis. laMinim fugiatEnim qui irure incididunt ex proident qui reprehenderit enim. deserunt irure mollit do aute do voluptate sint veniam commodo excepteur officia.borum mollit aute eu ea dolor adipisicing et.na Cupidatat nostrud adipisicing nulla fugiat laboris laborum aliquip adipisicing minim incididunt laboris.non ipsum dolore anim eiusmod velit amet enim veniam ut ad est.fugiat nisi elit nisi non aliqua qui duis et consectetur.Labore proident qui id ad laborum mollit amet do officia sint qui mollit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cillum ex qui pariatur sint est elit amet commodo dolore duis exercitation cupidatat anim deserunt. Commodo mollit labore et qui sit consectetur laborum eiusmod.',
				content:
					'Paritur Lorem sint commodo deserunt duis nostrud. Quis cillum veniam dolor amet elit nulla. Pariatur sunt ex non minim labore et exercitation quis velit duis. Nisi minim commodo anim aute quis incididunt proident enim adipisicing eu do. Mollit tempor minim anim deserunt adipisicing. Magna esse labore eiusmod irure sunt cupidatat non et labore. Pariatur consectetur cupidatat ullamco dolor sit commodo proident cupidatat nulla occaecat qui ea. Ad nostrud magna quis anim veniam laboris do sint cillum nisi. Et sint enim eu proident ipsum. Deserunt ad ex non aliquip fugiat eiusmod tempor fugiat est et excepteur consequat excepteur ipsum.Quis consectetur nostrud proident laboris veniam eiusmod ullamco culpa esse reprehenderit esse proident sint. Ea aliqua laboris veniam tempor eiusmod sunt consequat nisi mollit. Veniam enim est cillum mollit sunt in non. Elit voluptate aliquip sunt fugiat aliqua elit incididunt fugiat ipsum eu mollit tempor. Officia magna est est cillum qui amet fugiat quis. Consectetur quis deserunt enim eiusmod est est sint quis consectetur nulla ea non. Magna ipsum aute laborum nisi duis tempor dolor ad cupidatat quis et pariatur.Sit ad irure laborum minim deserunt aute mollit fugiat minim laboris. Laborum aliqua occaecat dolore esse exercitation do elit aliquip amet proident laborum sint. Aute do cupidatat ut ea ipsum nisi veniam nulla ea est ex irure adipisicing adipisicing. In dolor aliquip non magna mollit reprehenderit sit fugiat excepteur. Pariatur tempor excepteur nulla tempor commodo reprehenderit deserunt sint nisi aute. Dolore est aliquip eu nisi ea nisi mollit culpa magna. ',
				dictionaryDownloadButtonProps: mockDictionaryDownloadButtonProps,
			},
			{
				title: '{An_unnecessarily_lengthy_name_for_a_schema:with_it’s_name_include_of_course}',
				openOnInit: false,
				description:
					'{Schema: description} Do MagNisiDoAmet sit adipisicing dolore incididunt minim.lore pariatur sit ex eiusmod Lorem do voluptate id aliquip occaecat duis. laMinim fugiatEnim qui irure incididunt ex proident qui reprehenderit enim. deserunt irure mollit do aute do voluptate sint veniam commodo excepteur officia.borum mollit aute eu ea dolor adipisicing et.na Cupidatat nostrud adipisicing nulla fugiat laboris laborum aliquip adipisicing minim incididunt laboris.non ipsum dolore anim eiusmod velit amet enim veniam ut ad est.fugiat nisi elit nisi non aliqua qui duis et consectetur.Labore proident qui id ad laborum mollit amet do officia sint qui mollit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cillum ex qui pariatur sint est elit amet commodo dolore duis exercitation cupidatat anim deserunt. Commodo mollit labore et qui sit consectetur laborum eiusmod.',
				content:
					'Paritur Lorem sint commodo deserunt duis nostrud. Quis cillum veniam dolor amet elit nulla. Pariatur sunt ex non minim labore et exercitation quis velit duis. Nisi minim commodo anim aute quis incididunt proident enim adipisicing eu do. Mollit tempor minim anim deserunt adipisicing. Magna esse labore eiusmod irure sunt cupidatat non et labore. Pariatur consectetur cupidatat ullamco dolor sit commodo proident cupidatat nulla occaecat qui ea. Ad nostrud magna quis anim veniam laboris do sint cillum nisi. Et sint enim eu proident ipsum. Deserunt ad ex non aliquip fugiat eiusmod tempor fugiat est et excepteur consequat excepteur ipsum.Quis consectetur nostrud proident laboris veniam eiusmod ullamco culpa esse reprehenderit esse proident sint. Ea aliqua laboris veniam tempor eiusmod sunt consequat nisi mollit. Veniam enim est cillum mollit sunt in non. Elit voluptate aliquip sunt fugiat aliqua elit incididunt fugiat ipsum eu mollit tempor. Officia magna est est cillum qui amet fugiat quis. Consectetur quis deserunt enim eiusmod est est sint quis consectetur nulla ea non. Magna ipsum aute laborum nisi duis tempor dolor ad cupidatat quis et pariatur.Sit ad irure laborum minim deserunt aute mollit fugiat minim laboris. Laborum aliqua occaecat dolore esse exercitation do elit aliquip amet proident laborum sint. Aute do cupidatat ut ea ipsum nisi veniam nulla ea est ex irure adipisicing adipisicing. In dolor aliquip non magna mollit reprehenderit sit fugiat excepteur. Pariatur tempor excepteur nulla tempor commodo reprehenderit deserunt sint nisi aute. Dolore est aliquip eu nisi ea nisi mollit culpa magna. ',
				dictionaryDownloadButtonProps: mockDictionaryDownloadButtonProps,
			},
			{
				title: '{An_unnecessarily_lengthy_name_for_a_schema:with_it’s_name_include_of_course}',
				openOnInit: false,
				description:
					'{Schema: description} Do MagNisiDoAmet sit adipisicing dolore incididunt minim.lore pariatur sit ex eiusmod Lorem do voluptate id aliquip occaecat duis. laMinim fugiatEnim qui irure incididunt ex proident qui reprehenderit enim. deserunt irure mollit do aute do voluptate sint veniam commodo excepteur officia.borum mollit aute eu ea dolor adipisicing et.na Cupidatat nostrud adipisicing nulla fugiat laboris laborum aliquip adipisicing minim incididunt laboris.non ipsum dolore anim eiusmod velit amet enim veniam ut ad est.fugiat nisi elit nisi non aliqua qui duis et consectetur.Labore proident qui id ad laborum mollit amet do officia sint qui mollit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cillum ex qui pariatur sint est elit amet commodo dolore duis exercitation cupidatat anim deserunt. Commodo mollit labore et qui sit consectetur laborum eiusmod.',
				content:
					'Paritur Lorem sint commodo deserunt duis nostrud. Quis cillum veniam dolor amet elit nulla. Pariatur sunt ex non minim labore et exercitation quis velit duis. Nisi minim commodo anim aute quis incididunt proident enim adipisicing eu do. Mollit tempor minim anim deserunt adipisicing. Magna esse labore eiusmod irure sunt cupidatat non et labore. Pariatur consectetur cupidatat ullamco dolor sit commodo proident cupidatat nulla occaecat qui ea. Ad nostrud magna quis anim veniam laboris do sint cillum nisi. Et sint enim eu proident ipsum. Deserunt ad ex non aliquip fugiat eiusmod tempor fugiat est et excepteur consequat excepteur ipsum.Quis consectetur nostrud proident laboris veniam eiusmod ullamco culpa esse reprehenderit esse proident sint. Ea aliqua laboris veniam tempor eiusmod sunt consequat nisi mollit. Veniam enim est cillum mollit sunt in non. Elit voluptate aliquip sunt fugiat aliqua elit incididunt fugiat ipsum eu mollit tempor. Officia magna est est cillum qui amet fugiat quis. Consectetur quis deserunt enim eiusmod est est sint quis consectetur nulla ea non. Magna ipsum aute laborum nisi duis tempor dolor ad cupidatat quis et pariatur.Sit ad irure laborum minim deserunt aute mollit fugiat minim laboris. Laborum aliqua occaecat dolore esse exercitation do elit aliquip amet proident laborum sint. Aute do cupidatat ut ea ipsum nisi veniam nulla ea est ex irure adipisicing adipisicing. In dolor aliquip non magna mollit reprehenderit sit fugiat excepteur. Pariatur tempor excepteur nulla tempor commodo reprehenderit deserunt sint nisi aute. Dolore est aliquip eu nisi ea nisi mollit culpa magna. ',
				dictionaryDownloadButtonProps: mockDictionaryDownloadButtonProps,
			},
			{
				title: '{An_unnecessarily_lengthy_name_for_a_schema:with_it’s_name_include_of_course}',
				openOnInit: false,
				description:
					'{Schema: description} Do MagNisiDoAmet sit adipisicing dolore incididunt minim.lore pariatur sit ex eiusmod Lorem do voluptate id aliquip occaecat duis. laMinim fugiatEnim qui irure incididunt ex proident qui reprehenderit enim. deserunt irure mollit do aute do voluptate sint veniam commodo excepteur officia.borum mollit aute eu ea dolor adipisicing et.na Cupidatat nostrud adipisicing nulla fugiat laboris laborum aliquip adipisicing minim incididunt laboris.non ipsum dolore anim eiusmod velit amet enim veniam ut ad est.fugiat nisi elit nisi non aliqua qui duis et consectetur.Labore proident qui id ad laborum mollit amet do officia sint qui mollit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cillum ex qui pariatur sint est elit amet commodo dolore duis exercitation cupidatat anim deserunt. Commodo mollit labore et qui sit consectetur laborum eiusmod.',
				content:
					'Paritur Lorem sint commodo deserunt duis nostrud. Quis cillum veniam dolor amet elit nulla. Pariatur sunt ex non minim labore et exercitation quis velit duis. Nisi minim commodo anim aute quis incididunt proident enim adipisicing eu do. Mollit tempor minim anim deserunt adipisicing. Magna esse labore eiusmod irure sunt cupidatat non et labore. Pariatur consectetur cupidatat ullamco dolor sit commodo proident cupidatat nulla occaecat qui ea. Ad nostrud magna quis anim veniam laboris do sint cillum nisi. Et sint enim eu proident ipsum. Deserunt ad ex non aliquip fugiat eiusmod tempor fugiat est et excepteur consequat excepteur ipsum.Quis consectetur nostrud proident laboris veniam eiusmod ullamco culpa esse reprehenderit esse proident sint. Ea aliqua laboris veniam tempor eiusmod sunt consequat nisi mollit. Veniam enim est cillum mollit sunt in non. Elit voluptate aliquip sunt fugiat aliqua elit incididunt fugiat ipsum eu mollit tempor. Officia magna est est cillum qui amet fugiat quis. Consectetur quis deserunt enim eiusmod est est sint quis consectetur nulla ea non. Magna ipsum aute laborum nisi duis tempor dolor ad cupidatat quis et pariatur.Sit ad irure laborum minim deserunt aute mollit fugiat minim laboris. Laborum aliqua occaecat dolore esse exercitation do elit aliquip amet proident laborum sint. Aute do cupidatat ut ea ipsum nisi veniam nulla ea est ex irure adipisicing adipisicing. In dolor aliquip non magna mollit reprehenderit sit fugiat excepteur. Pariatur tempor excepteur nulla tempor commodo reprehenderit deserunt sint nisi aute. Dolore est aliquip eu nisi ea nisi mollit culpa magna. ',
				dictionaryDownloadButtonProps: mockDictionaryDownloadButtonProps,
			},
		],
	},
};
export const Empty: Story = {
	args: { accordionItems: [] },
};
