name: pcgl-dictionary-manager
version: '2'

services:
  lecternDb:
    container_name: lectern-mongo
    image: bitnami/mongodb:4.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: lectern
      MONGODB_ROOT_PASSWORD: password123
volumes:
  mongodb_data:
    name: lectern-mongo-data
    driver: local
